### ISSUE TITLE
:white_check_mark: Breadboard Experiments

### ISSUE THREAD

**Issue by penguineer** [moPsy-project/manual-gate-trigger-source#9]
Go to the lab (aka [Netz39 Hackerspace](https://www.netz39.de)) and do the following experiments:

- [x] Verify the gate/trigger input is working as intended → https://github.com/moPsy-project/manual-gate-trigger-source/issues/9#issuecomment-1379484607
  - [x] Verify the manual trigger has no bounce effects
  - [x] Verify the gate switch is working as intended
  - [x] Check the signal polarity on the trigger input
  - [x] Check if LPF is needed
  - [x] Fix manual switch circuit → https://github.com/moPsy-project/manual-gate-trigger-source/pull/18
- [x] Verify the op-amp gate length generator → https://github.com/moPsy-project/manual-gate-trigger-source/issues/9#issuecomment-1376312371
  - [x] Verify the circuit is working as intended
  - [x] Check the signal polarity 
  - ~~Check if circuit timing is accurate under trigger output load~~
- [x] Verify the 555 gate length generator → https://github.com/moPsy-project/manual-gate-trigger-source/issues/9#issuecomment-1377659194
  - [x] Verify the circuit is working as intended
  - [x] Check the signal polarity
  - [x] Tune the RC values
- [x] Verify the voltage source → https://github.com/moPsy-project/manual-gate-trigger-source/issues/9#issuecomment-1378058845
  - [x] Verify the voltages can be generated and adjusted easily
  - [x] Check output behavior when switching voltages
  - [x] Verify circuit is stable under load
  - [x] Check if LPF is needed
  - [x] Check if feedback capacitor is needed
- [x] Verify gate/trigger output → https://github.com/moPsy-project/manual-gate-trigger-source/issues/9#issuecomment-1379542623
  - [x] Check polarity and verify it matches
  - [x] Verify step behaviour
  - [x] Verify that voltages are output correctly
  - [x] Investigate behavior with changing collector voltages
  - [x] Verify the push-pull behaviour (see b139e5046e6c81cfce74a07d63c053a551c30660)
- ~~Verify transient behavior for power supply filter~~ → Go with the Befaco-inspired design for now. PSU filtering is a bigger topic for another (soon) time.

**Comment by penguineer** [comment]
# Verify the op-amp gate length generator

## Setup
The op-amp based pulse generator has been set up on a breadboard with one modification: The timing capacity is set against V- instead if GND to observe polarity, as an electrolytic capacitor was used.

![opamp-monoflop-breadboard](https://user-images.githubusercontent.com/2039739/211406057-3032049b-fee1-4ea4-96c0-5b6899ab70a7.jpg)

It could be verified that the circuit behaves as described.

## Polarity

The specific TL072 used in this experiment could swing up to 1V towards the rails, so the upper output was kept at 11V towards V+ and the lower output was kept at -11V towards V-.

In it's stable state the circuit outputs V+. If the input goes sufficiently below 0V/GND, the output swings towards V- until the set time has run out, then swings back to +V.

In this sense it has a negative polarity.

## Measurement

The circuit has been measured with its output at channel 1 (yellow) and the timing capacitor at channel 2 (cyan).
![opamp-monoflop-measurement](https://user-images.githubusercontent.com/2039739/211407028-fc7c461a-1941-4ac2-8fbd-43b654e9d9c0.jpg)

 Overall the behaviour is as expected. Timing is accurate.
 
Two negative observations:
* There is a slight ringing in the edges (only slightly visible in the shown measurement), which may be due to the fact that this op-amp is not ideal in a comperator setting.
* While the edge is triggered, the output is slightly below its stable value. While this would be compensated by the output circuit, it is not ideal.

It has also been observed that the trigger reacts to the rising edge, i.e. the end of the trigger pulse and is kept at stable level until that pulse has ended.

## Conclusion

While the circuit behaves as described, it's re-trigger behaviour makes it not suitable for the use case.

Since this variant will not be chosen, the accuracy under load has not been measured.

**Comment by penguineer** [comment]
# Verify the 555 gate length generator

## Setup

The 555 based generator has been set up on  a breadboard as is.
![IMG_20230110_190208](https://user-images.githubusercontent.com/2039739/211628464-da465d8f-d90a-475e-82b0-010728584872.jpg)

## Polarity and behavior

The monoflop triggers on a falling edge (V+ → GND) and outputs a rising pulse (GND → V+ → GND).
If the trigger is held, the output stays at V+ until the trigger is released or the pulse times out, whichever comes _last_.

## Measurement
![IMG_20230110_185816](https://user-images.githubusercontent.com/2039739/211628923-8116d640-d10d-4b1c-a6d4-6d2c43db8a8f.jpg)

The output signal (channel 1, yellow) behaves as expected. 
Channel 2 (cyan) shows the timing capacitor.

## Conclusion

The circuit is usable with changes to the RC element:
* Change capacitor to 2u2
* Change series resistor to 2k2

It could also be shown that the push button as input trigger did not lead to bouncing, which is attributed to the (re-)triggering behavior of the monoflop.

**Comment by penguineer** [comment]
# Verify the voltage source

## Setup
![IMG_20230111_200031](https://user-images.githubusercontent.com/2039739/211896575-a38600ae-9974-45d9-ac13-2cc947aebf16.jpg)

The final circuit shown here has been merged in https://github.com/moPsy-project/manual-gate-trigger-source/pull/14. Additional components:
* Output stage with load of four short-circuit outputs (worst case scenario)
* Push button for trigger simulation
* Simple SPDT (ON/OFF/ON) switch to simulate voltage selection.

The switch for voltage selection is similar to the final switch.

## LPF measurements

The switch behaviour without LPF is as follows:
![IMG_20230111_182111](https://user-images.githubusercontent.com/2039739/211897534-6d8fc8d0-a43c-4623-9b45-938d118cd247.jpg)

A bouncing effect is clearly visible.

With the LPF the switch behaviour is smooth:
![IMG_20230111_182813](https://user-images.githubusercontent.com/2039739/211897780-7498dc83-1eed-48f3-b40b-f7314e72f16e.jpg)


## Voltage selection

Voltage selection has been verified in a spice simulation. All voltages could be selected within 80% of the potentiometer range.

## Feedback Capacitor

Experiments in #3 have shown that the 330p feedback capacitor is not needed.

## Behaviour under load

With load, a ripple effect was visible. This could be solved by adding a 10u filter capacitor.

The output behavior with a BC337 output stage and 80mA load shows some decay effect, but is sufficiently fast (200 ns switching time).

![IMG_20230111_195701](https://user-images.githubusercontent.com/2039739/211899211-b740fb19-9fed-4ec6-8c52-5ae8a50d3485.jpg)

![IMG_20230111_195714](https://user-images.githubusercontent.com/2039739/211900187-c36fc1d5-f87b-4a75-adff-1f3735d685c5.jpg)

## Conclusion

With the modification in https://github.com/moPsy-project/manual-gate-trigger-source/pull/14 the circuit is usable and runs stable.

**Comment by penguineer** [comment]
# Verify the gate/trigger input is working as intended

## Switching Behaviour

![IMG_20230111_215928](https://user-images.githubusercontent.com/2039739/211917278-87ac0e11-ccd1-4a5f-9823-15cd784f2797.jpg)

The leading edge is very sharp and sufficient for our application.

![IMG_20230111_220004](https://user-images.githubusercontent.com/2039739/211917591-44a97883-7537-42fa-b951-d56891e7457e.jpg)

The trailing edge is rather slow. However, the change is finished in 50us, which is much shorter than the 1ms minimal gate length.

## Polarity

After a correction (https://github.com/moPsy-project/manual-gate-trigger-source/pull/15) in the schematic the input has the desired inverting polarity.

## Is the LPF needed?

The following measurements have been done with a [Cherry MX blue](https://www.cherrymx.de/cherry-mx/mx-original/mx-blue.html) switch and the gate generator circuit from the schematic with R=4k7 and C=200n.

### Switch-On Characteristics

Closing the switch by itself has a slight bouncing effect, which is, however, well above the trigger threshold.
![IMG_20230117_142430](https://user-images.githubusercontent.com/2039739/212915643-a27b0ac0-10e2-4b70-be29-bbbf6bab54e8.jpg)

With the HPF for trigger generation the result looks like this:
![IMG_20230117_142930](https://user-images.githubusercontent.com/2039739/212915842-52965b15-f6a4-4a7a-905a-1d69d7a653b1.jpg)

Similar with gate generation:
![IMG_20230117_143010](https://user-images.githubusercontent.com/2039739/212915953-21ae66d7-7f74-4edf-b094-e3eb7f9ba8c6.jpg)

There are no double-trigger effects, so switch-on behaviour is clean even with bouncing.

### Switch-Off Characteristics

Releasing the switch by itself has the following characteristic:
![IMG_20230117_142410](https://user-images.githubusercontent.com/2039739/212916166-2ebd92d4-a743-4537-9cee-377bb006bc0f.jpg)

The slow drop might be due to the bull capaccitor.

As shown above, this has no negative effects when in the trigger mode.

In gate mode many measurements look like this:
![IMG_20230117_143948](https://user-images.githubusercontent.com/2039739/212916526-4e6f4123-35c8-4044-aa2c-fc22098b7026.jpg)

However, there is a slight chance of re-triggering:
![IMG_20230117_143938](https://user-images.githubusercontent.com/2039739/212916607-71157250-2bcc-46b5-8d93-5d2a5ac214c0.jpg)

This effect is not acceptable, as following modules will react to this additional gate. Releasing the button must not induce an extra gate or trigger!

Some adjustments and tuning was necessary to remedy this issue.

## Conclusion

The circuit works as intended and has the desired switching behaviour after tuning in 177a026b595e051d070c927005f1d1f96c011d68.

**Comment by penguineer** [comment]
# Verify gate/trigger output

## Setup

The adapted circuit from https://github.com/moPsy-project/manual-gate-trigger-source/pull/16 has been set up on a breadboard.

## Switching behavior
![IMG_20230111_223639](https://user-images.githubusercontent.com/2039739/211927255-b03c80df-9e70-4198-a0a2-4dbe72af4519.jpg)
![IMG_20230111_223630](https://user-images.githubusercontent.com/2039739/211927277-b61e806a-79e1-49d3-beb5-ce4b3c5afa0e.jpg)

Switching is sufficiently fast.

The polarity matches the 555 output.

Please note that these measurements have been done with BC337/BC227 replacements.

## Conclusion

The push-pull setup is usable.

**Comment by penguineer** [comment]
# Final output signal

## Raising edge
![IMG_20230117_194602](https://user-images.githubusercontent.com/2039739/212992535-c894ef7d-f0e7-4f0d-b4f3-30b926e7e190.jpg)

## Falling edge
![IMG_20230117_194631](https://user-images.githubusercontent.com/2039739/212992556-6cc272c4-627d-4c07-8d8f-d06c58ca1f32.jpg)

## Shortest trigger pulse
![IMG_20230117_194538](https://user-images.githubusercontent.com/2039739/212992581-ed456484-c2f6-40cc-a5b8-8f89f6b6e53c.jpg)

**Comment by penguineer** [comment]
#Final Breadboard setup

![IMG_20230117_202128](https://user-images.githubusercontent.com/2039739/212993338-b2a3b371-a56f-4afa-86a7-eea9575f3fd6.jpg)
